name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x, 22.x, 23.x]

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, and test
      run: |
        npm ci
        npm run vulnerabilities
        npm run lint
        npm run cpd
        npm test
      env:
        CI: true
